=== bltzr-gg/token-sale-portal/apps/token-sale/src/tokenlist.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://github.com/SmolDapp/tokenLists/blob/main/scripts/schema.json",
  "title": "Tokenlistooor",
  "description": "Schema for lists of tokens compatible with the Uniswap Interface",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "description": "The name of the token list",
      "minLength": 1,
      "pattern": "^[\\w ]+$"
    },
    "timestamp": {
      "type": "string",
      "format": "date-time",
      "description": "The timestamp of this list version; i.e. when this immutable version of the list was created"
    },
    "version": {
      "type": "object",
      "description": "The version of the list, used in change detection",
      "examples": [{ "major": 1, "minor": 0, "patch": 0 }],
      "additionalProperties": false,
      "properties": {
        "major": {
          "type": "integer",
          "description": "The major version of the list. Must be incremented when tokens are removed from the list or token addresses are changed.",
          "minimum": 0
        },
        "minor": {
          "type": "integer",
          "description": "The minor version of the list. Must be incremented when tokens are added to the list.",
          "minimum": 0
        },
        "patch": {
          "type": "integer",
          "description": "The patch version of the list. Must be incremented for any changes to the list.",
          "minimum": 0
        }
      },
      "required": ["major", "minor", "patch"]
    },
    "tokens": {
      "type": "array",
      "description": "The list of tokens included in the list",
      "items": {
        "type": "object",
        "description": "Metadata for a single token in a token list",
        "additionalProperties": false,
        "properties": {
          "chainId": {
            "type": "integer",
            "description": "The chain ID of the Ethereum network where this token is deployed",
            "minimum": 1
          },
          "address": {
            "type": "string",
            "description": "The checksummed address of the token on the specified chain ID",
            "pattern": "^0x[a-fA-F0-9]{40}$"
          },
          "decimals": {
            "type": "integer",
            "description": "The number of decimals for the token balance",
            "minimum": 0,
            "maximum": 255
          },
          "name": {
            "type": "string",
            "description": "The name of the token",
            "minLength": 1
          },
          "symbol": {
            "type": "string",
            "description": "The symbol for the token; must be alphanumeric",
            "minLength": 1
          },
          "logoURI": {
            "type": "string",
            "description": "A URI to the token logo asset; if not set, interface will attempt to find a logo based on the token address; suggest SVG or PNG of size 64x64"
          }
        },
        "required": ["chainId", "address", "decimals", "name", "symbol"]
      },
      "minItems": 1
    },
    "keywords": {
      "type": "array",
      "items": { "type": "string" }
    },
    "tags": {
      "type": "array",
      "items": { "type": "string" }
    },
    "logoURI": {
      "type": "string",
      "description": "A URI for the logo of the token list; prefer SVG or PNG of size 256x256",
      "format": "uri"
    }
  },
  "required": ["name", "timestamp", "version", "tokens"]
}

=== bltzr-gg/token-sale-portal/apps/token-sale/public/sepolia-tokens.json
{
  "name": "RWG Sepolia Custom Tokens",
  "logoURI": "https://token-sale-portal.vercel.app/logo-1.png",
  "version": {
    "major": 1,
    "minor": 0,
    "patch": 0
  },
  "keywords": ["rwg", "real world gaming", "$REAL"],
  "timestamp": "2025-04-01T00:00:00+00:00",
  "tokens": [
    {
      "chainId": 11155111,
      "address": "0x6a0d40eeaef86b1e4356e8b17e190e36cba04298",
      "name": "Testnet USDC",
      "symbol": "USDC",
      "decimals": 18,
      "logoURI": "https://cryptologos.cc/logos/usd-coin-usdc-logo.png?v=040"
    }
  ]
}
